In [221]:
import pandas as pd 
import numpy  as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# Define a function to read files of any extension
def readFile(fileNmae):
    df=None 
    extension = fileNmae.split('.')[-1]
    try:
        if extension == 'csv':
            df=pd.DataFrame(pd.read_csv(fileNmae))
        elif extension == 'xls' or extension == 'xlsx':
            df=pd.DataFrame(pd.read_excel(fileNmae))
        elif extension == 'json':
            df=pd.DataFrame(pd.read_json(fileNmae))
        elif extension == 'sql':
            df=pd.DataFrame(pd.read_sql(fileNmae))
        elif extension == 'html':
            df=pd.DataFrame(pd.read_html(fileNmae))
        elif extension == 'feather':
            df=pd.DataFrame(pd.read_feather(fileNmae))
        elif extension == 'spss':
            df=pd.DataFrame(pd.read_spss(fileNmae))
        else:
            return 'Sorry, I can only read files with the extension: .csv, .xls or .xlsx, .json, .sql, .html, .feather, .spss'
    except FileNotFoundError :
        print('The file does not exist or you made a mistake in the file name')
    return df


# Define a function to Summary Data 
def dataSummary(data , columns=None):
    if not isinstance(data, pd.DataFrame):
        data = pd.DataFrame(data)
    # Summary statistics
    print('Summary Statistics:')
    print(data.describe())
    print('\n')
    
    # Average
    if columns is None:
        print('You need to select numeric columns in function to calculate the average\n')
    else:
        for column in columns:
            print('Average (Mean) Values:')
            if all(isinstance(x, int) for x in columns):
                avg = data.iloc[ : ,column].mean()
            else:
                avg = data.loc[ : ,column.replace(" ", "")].mean()
            print(f"Column '{column}': {avg}")
    print('\n')
    # Most frequent values
    print('Most Frequent Values:')
    for column in data.columns:
        most_frequent = data[column].mode()
        print(f"Column '{column}':")
        print(most_frequent)
    print('\n')
# Define a function to Handling the missing value 
def handlingMissingValues(data,strategy='remove any'):
    print('Missing Values are: ',data.isna().sum())
    print(data.isna())
    if strategy == 'remove any':
        data=data.dropna()
    elif strategy == 'remove all':
        data=data.dropna(how='all')
    elif strategy == 'fill with':
        data=data.fillna(input('You Want to fill it with:'))
    else:
        print("Please enter one of the strategies below")
        print("'remove any' - remove rows with any missing values (default)")
        print("'remove all' - remove rows with all missing values")
        print("'fill with' - fill it with a specific value")
    return data
def dataEncoding(data,columns=[1]):
    try:
        ct=ColumnTransformer(transformers=[('encoder' , OneHotEncoder() ,columns )] , remainder='passthrough')
        encodingData=np.array(ct.fit_transform(data))
        return encodingData
    except:
        print('You must enter a list of column numbers from 1 to ',data.shape[1]-1 ,'\nAnd you can only decoding 5 columns in the sametime and the list number must be serial')

#Test the functions
#1. Data Reading:
data_1=readFile('loan_data.csv')
print(data_1)

      Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001003    Male     Yes          1      Graduate            No   
1    LP001005     NaN     Yes        NaN      Graduate           Yes   
2    LP001006    Male     Yes          0  Not Graduate            No   
3    LP001008    Male      No          0      Graduate            No   
4    LP001013    Male     Yes          0  Not Graduate            No   
..        ...     ...     ...        ...           ...           ...   
376  LP002953    Male     Yes         3+      Graduate            No   
377  LP002974    Male     Yes          0      Graduate            No   
378  LP002978  Female      No          0      Graduate            No   
379  LP002979    Male     Yes         3+      Graduate            No   
380  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             4583.0             1508.0         128           

In [222]:
data_2=readFile('childrens_violence new.xlsx')
print(data_2)

           Entity Code  Year  Childrens Violent Discipline Rate\n\n\n\n\n\n
0         Georgia  GEO  2005                                             67
1      Tajikistan  TJK  2005                                             78
2      Azerbaijan  AZE  2006                                             77
3    Burkina Faso  BFA  2006                                             83
4   Cote d'Ivoire  CIV  2006                                             91
..            ...  ...   ...                                            ...
68          Sudan  SDN  2014                                             64
69           Togo  TGO  2014                                             81
70        Vietnam  VNM  2014                                             68
71       Zimbabwe  ZWE  2014                                             63
72          Congo  COG  2015                                             83

[73 rows x 4 columns]


In [223]:
data_3=readFile('intents.json')
print(data_3)

                                              intents
0   {'tag': 'greeting', 'patterns': ['Hi', 'How ar...
1   {'tag': 'goodbye', 'patterns': ['cya', 'see yo...
2   {'tag': 'creator', 'patterns': ['what is the n...
3   {'tag': 'name', 'patterns': ['name', 'your nam...
4   {'tag': 'hours', 'patterns': ['timing of colle...
5   {'tag': 'number', 'patterns': ['more info', 'c...
6   {'tag': 'course', 'patterns': ['list of course...
7   {'tag': 'fees', 'patterns': ['information abou...
8   {'tag': 'location', 'patterns': ['where is the...
9   {'tag': 'hostel', 'patterns': ['hostel facilit...
10  {'tag': 'event', 'patterns': ['events organise...
11  {'tag': 'document', 'patterns': ['document to ...
12  {'tag': 'floors', 'patterns': ['size of campus...
13  {'tag': 'syllabus', 'patterns': ['Syllabus for...
14  {'tag': 'library', 'patterns': ['is there any ...
15  {'tag': 'infrastructure', 'patterns': ['how is...
16  {'tag': 'canteen', 'patterns': ['food faciliti...
17  {'tag': 'menu', 'pattern

In [224]:
#2. Data Summary:
#the list of numbers select numeric columns in function to calculate the average
dataSummary(data ,[6,7,8,9])

Summary Statistics:
       ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       380.000000         381.000000  381.000000        370.000000   
mean       3581.371053        1277.275381  104.986877        340.864865   
std        1421.372837        2340.818114   28.358464         68.549257   
min         150.000000           0.000000    9.000000         12.000000   
25%        2595.750000           0.000000   90.000000        360.000000   
50%        3333.000000         983.000000  110.000000        360.000000   
75%        4291.000000        2016.000000  127.000000        360.000000   
max        9703.000000       33837.000000  150.000000        480.000000   

       Credit_History  
count      351.000000  
mean         0.837607  
std          0.369338  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000  


Average (Mean) Values:
Column '6': 3581.371052631579
Average (Mean) Values:
Column '7'

In [225]:
#3. Handling Missing Values:
clend_data=handlingMissingValues(data,'fill with')
print(clend_data)

Missing Values are:  Loan_ID               0
Gender                6
Married               0
Dependents            9
Education             0
Self_Employed        21
ApplicantIncome       1
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     11
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64
     Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0      False   False    False       False      False          False   
1      False    True    False        True      False          False   
2      False   False    False       False      False          False   
3      False   False    False       False      False          False   
4      False   False    False       False      False          False   
..       ...     ...      ...         ...        ...            ...   
376    False   False    False       False      False          False   
377    False   False    False       False      False          False   
378    False   

You Want to fill it with: TREE


      Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001003    Male     Yes          1      Graduate            No   
1    LP001005    TREE     Yes       TREE      Graduate           Yes   
2    LP001006    Male     Yes          0  Not Graduate            No   
3    LP001008    Male      No          0      Graduate            No   
4    LP001013    Male     Yes          0  Not Graduate            No   
..        ...     ...     ...        ...           ...           ...   
376  LP002953    Male     Yes         3+      Graduate            No   
377  LP002974    Male     Yes          0      Graduate            No   
378  LP002978  Female      No          0      Graduate            No   
379  LP002979    Male     Yes         3+      Graduate            No   
380  LP002990  Female      No          0      Graduate           Yes   

    ApplicantIncome  CoapplicantIncome  LoanAmount Loan_Amount_Term  \
0            4583.0             1508.0         128            36

In [226]:
#4. Categorical Data Encoding:
print(dataEncoding(data,[1,17]))

You must enter a list of column numbers from 1 to  12 
And you can only decoding 5 columns in the sametime and the list number must be serial
None


In [227]:
print(dataEncoding(data,[9,10,11,12]))

[[0.0 0.0 0.0 ... 4583.0 1508.0 128]
 [0.0 0.0 0.0 ... nan 0.0 66]
 [0.0 0.0 0.0 ... 2583.0 2358.0 120]
 ...
 [0.0 0.0 0.0 ... 2900.0 0.0 71]
 [0.0 0.0 0.0 ... 4106.0 0.0 40]
 [0.0 0.0 0.0 ... 4583.0 0.0 133]]
